### ISSUE TITLE
Optimise How you get the list of snapshots

### ISSUE THREAD

**Issue by marcoherbst** [ijunaid8088/extractor#1]
- [x] Probably by first requesting the entire list and second generating the requests.
- [x] calculate what the predicted # snapshots should be, so we know the  We got XX of YY .
- [ ] ~Make schedule component horizontal~ (Reasons there is no option available for this but we can create something for our own need which is called customView https://fullcalendar.io/docs/views/Custom_Views/) UPDATE
- [x] Schedule component can default to M-F 8:00-17:30

**Comment by ijunaid8989** [comment]
re:  calculate what the predicted # snapshots should be, so we know the We got XX of YY

This is never going to be right. or nearly right. Suppose you have requested snapshots with different frequency and the camera is recording images with different frequency. 

It's only going to be supposed value. which may be right or maybe not. Scientifically.. always wrong.

**Comment by marcoherbst** [comment]
I don't see your point.

The figure YY will be the theoretically correct amount.

The figure XX will be the actual value achieved which we know at the end of the extraction.

Or?

**Comment by ijunaid8989** [comment]
Okay right.. I got it now!

**Comment by ijunaid8989** [comment]
I have added optimization in getting the images. I am closing this issue and creating a new one. For any use case which may come as in future when SE will be used more often.
