### ISSUE TITLE
Posible misusage of cast/4

### ISSUE THREAD

**Issue by Hajto** [ijunaid8088/extractor#16]
https://github.com/ijunaid8989/extractor/blob/d4318c65d2fbd734db3ad234a8c6cc7b45c49f14/web/models/snapshot_extractor.ex#L54

https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/4

`cast/4` changed a bit, please put all updateable fields in 3rd param.

**Comment by ijunaid8989** [comment]
Its fixed now.
