### ISSUE TITLE
Save as a .json the instructions for that extract in the folder

### ISSUE THREAD

**Issue by marcoherbst** [ijunaid8088/extractor#2]
Save as a .json the instructions for that extract in the folder

**Comment by ijunaid8989** [comment]
And instructions are meant to be?

**Comment by marcoherbst** [comment]
the extract parameters. From , To, Freq, Sched ....

(it is also perfectly ok, and maybe better, to just have this visible in the admin report, but it needs to be somewhere)

m

**Comment by ijunaid8989** [comment]
Done.

**Comment by ijunaid8989** [comment]
I have added a .json file with name of instruction.json which will look like 

```
{"to_date":"Tuesday, Nov 22 2016, 00:00","schedule":{"Wednesday":[],"Tuesday":[],"Thursday":[],"Sunday":[],"Saturday":[],"Monday":["0:30-8:0"],"Friday":[]},"from_date":"Monday, Nov 21 2016, 00:00","frequency":"1 Frame Every 12 hour"}
```

it will be placed within extractor #number folder withing camera_exid folder.
